/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as StoresImport } from "./routes/stores";
import { Route as MenuImport } from "./routes/menu";
import { Route as FranchiseImport } from "./routes/franchise";
import { Route as EventImport } from "./routes/event";
import { Route as AboutImport } from "./routes/about";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const StoresRoute = StoresImport.update({
  path: "/stores",
  getParentRoute: () => rootRoute,
} as any);

const MenuRoute = MenuImport.update({
  path: "/menu",
  getParentRoute: () => rootRoute,
} as any);

const FranchiseRoute = FranchiseImport.update({
  path: "/franchise",
  getParentRoute: () => rootRoute,
} as any);

const EventRoute = EventImport.update({
  path: "/event",
  getParentRoute: () => rootRoute,
} as any);

const AboutRoute = AboutImport.update({
  path: "/about",
  getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      preLoaderRoute: typeof IndexImport;
      parentRoute: typeof rootRoute;
    };
    "/about": {
      preLoaderRoute: typeof AboutImport;
      parentRoute: typeof rootRoute;
    };
    "/event": {
      preLoaderRoute: typeof EventImport;
      parentRoute: typeof rootRoute;
    };
    "/franchise": {
      preLoaderRoute: typeof FranchiseImport;
      parentRoute: typeof rootRoute;
    };
    "/menu": {
      preLoaderRoute: typeof MenuImport;
      parentRoute: typeof rootRoute;
    };
    "/stores": {
      preLoaderRoute: typeof StoresImport;
      parentRoute: typeof rootRoute;
    };
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  AboutRoute,
  EventRoute,
  FranchiseRoute,
  MenuRoute,
  StoresRoute,
]);

/* prettier-ignore-end */
